# 线上配置文件

server:
  port: 8101
  servlet:
    context-path: /api
    session:
      cookie:
        domain: 106.52.221.21
        same-site: lax
        secure: false
spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.52.221.21:3306/bi
    username: bi
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: MainApplication
  # Redis 配置
  # todo 需替换配置
  redis:
    database: 1
    host: 106.52.221.21
    port: 6379
    timeout: 5000
    password: 123456

  session:
    timeout: 86400
    store-type: redis
    redis:
      namespace: spring:session
      flush-mode: on_save
mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
# 接口文档配置
knife4j:
  basic:
    enable: true
    username: root
    password: 123456
